/* Re-export shim — content lives in src/shared/domain/LintRules.ts. */

export {
	applicabilityRequiredRule,
	approvalRecordRules,
	assumptionDowngradeApprovalRule,
	baselineVersionRequiredRule,
	boundaryConcurrencyModelRule,
	boundaryPolicyRefRule,
	dataScopeRequiredRule,
	deprecatedFieldsRequiredRule,
	debtBudgetFormRule,
	fieldTypeRules,
	generatedArtifactSurfaceRefRule,
	lifecycleFieldOrphanRule,
	lifecycleStatusRules,
	migrationCrossPartitionRule,
	migrationEnforcementStageRule,
	NORMATIVE_SECTIONS,
	openQBlockingRule,
	partitionDefaultPolicySetRule,
	REQUIRED_PARTITION_SECTIONS,
	sectionViolations,
	testObligationRules,
	WEASEL_ABSOLUTE,
	WEASEL_MODAL_IN_NORMATIVE,
	WEASEL_WORDS,
	weaselFindings,
	type SectionViolation,
	type WeaselFinding,
} from "../../../shared/domain/LintRules.js";
